### ISSUE TITLE
Does auth tokens ever gets updated?

### ISSUE THREAD

**Issue by ziyafenn** [XboxReplay/xboxlive-auth#1]
Hello. Thanks for the great library. I wanted to know if the auth tokens after signing in for the first time gets updated?

Thanks.

**Comment by Alexis-Bize** [comment]
Hey @ziyafenn! Thanks for your feedback :)

Right, I omitted this point. Once generated the token will be valid for the next 14 days (this may change) so you must handle this case on your side and generate a new one if required.

I'll update the library to return the lifetime.

**Comment by Alexis-Bize** [comment]
@ziyafenn Here you go! 

<img width="569" alt="Capture d’écran 2019-04-04 à 16 40 29" src="https://user-images.githubusercontent.com/1816892/55564529-60f41d80-56f8-11e9-8980-fc3f3a5542cf.png">
