### ISSUE TITLE
NPM error

### ISSUE THREAD

**Issue by DrMoraschi** [XboxReplay/xboxlive-auth#11]
Can you take a look at this issue when you have time? Thanks

https://github.com/PrismarineJS/mineflayer/issues/1577#issue-782047319

**Comment by Alexis-Bize** [comment]
Oh, thanks a lot! A fix will be deployed asap.

**Comment by DrMoraschi** [comment]
Ty :)

**Comment by Alexis-Bize** [comment]
The issue has been resolved, thanks one again for the report.

**Comment by DrMoraschi** [comment]
Np and thanks to you :D
