### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by nekiak** [XboxReplay/xboxlive-auth#13]
I made an issue in the mineflayer repo about this. Apparently it's an issue with this library.
https://github.com/PrismarineJS/mineflayer/issues/1549

**Comment by Alexis-Bize** [comment]
I could not reproduce the issue with the latest `3.3.3` version, nor `3.3.0`. As you made a fresh Microsoft account, did you:
* Linked a gamertag to it?
* Took a look at this section?: https://github.com/XboxReplay/xboxlive-auth#im-unable-to-connect-even-with-valid-credentials-and-no-2fa

Thanks!

**Comment by Alexis-Bize** [comment]
Also: Are you 18 or older? If not, try to change your registred birthday (via MS settings page). Seems like "non Adult" accounts can not authenticate (TBC).

**Comment by nekiak** [comment]
Well, for some weird reason it's working now with the latest `3.3.3` version?
