### ISSUE TITLE
Improve reliability and errors of logins

### ISSUE THREAD

**Issue by rom1504** [XboxReplay/xboxlive-auth#14]
As explained in this issue more in detail https://github.com/PrismarineJS/node-minecraft-protocol/issues/791 we're encountering issues where some users cannot login with a `(node:2052) UnhandledPromiseRejectionWarning: Error: Unable to authenticate with Xbox Live: {"statusCode":401,"reason":"UNAUTHORIZED"}` error.
Ideally, all cases would be handled, but at least it would be quite useful if the lib could fail gracefully and put more information in the error as to what failed exactly, so depending libs could handle it in another way (for example by providing the user a login URL)

**Comment by Alexis-Bize** [comment]
Hey @rom1504, actually the lib tells you exactly what happened (`err.message`). Unfortunately `node-minecraft-protocol` only relies on `err.details - https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client/microsoftAuth.js#L25

![Screen Shot 2021-01-14 at 08 59 27](https://user-images.githubusercontent.com/1816892/104560883-d3708c00-5646-11eb-873a-59e8e6eba20d.png)

**Comment by rom1504** [comment]
Ah great, will change that
