### ISSUE TITLE
Upcoming 4.0.0 version - Details

### ISSUE THREAD

**Issue by Alexis-Bize** [XboxReplay/xboxlive-auth#15]
* Branch: https://github.com/XboxReplay/xboxlive-auth/tree/4.0.0

# Documentation
* https://github.com/XboxReplay/xboxlive-auth/tree/4.0.0/docs

# Breaking changes:
* ~[Exposed `authenticate` method will return "live" and "xboxlive" raw exchange responses](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/src/index.ts#L91)~
* [`authenticate` method response schema updated](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/docs/01-Authenticate.md#sample-response)

# Upcoming features:
* [Return each exchange response](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/docs/01-Authenticate.md#sample-response-raw)
* [Custom Azure application support](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/docs/02-Custom_Azure_Application.md)
* [Refresh token support (live)](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/src/core/live/index.ts#L75)
* [Electron App - Example](https://github.com/XboxReplay/xboxlive-auth/tree/4.0.0/examples/electron-app)

# Experimental:
* [Create a dummy Win32 device token](https://github.com/XboxReplay/xboxlive-auth/blob/4.0.0/src/core/xboxlive/index.ts#L160)

**Comment by wescopeland** [comment]
Hi @Alexis-Bize! Thank you for putting in the time and effort to build this package; I am using it to great affect on a new project for the last month.

Because I want to use 4.0.0, I've cloned the 4.0.0 branch and am storing the library locally in my project's monorepo. Is there any chance 4.0.0 could be published to npm, even if only tagged as a "next" release and not the main line?

**Comment by Alexis-Bize** [comment]
Hey @wescopeland, thanks a lot :)

Please note that the 4.0.0 version is already available on npm.
You can install it using `npm install @xboxreplay/xboxlive-auth@4.0.0-beta.5` command.

To be honest this version seems stable for a while now so I'll try to publish it as soon as possible.

**Comment by Gurrman375** [comment]
How exactly does generating an exprimental work? What are you send and what do you receive back? Just wanted to know because I'm trying to figure out device, title, and user tokens.

**Comment by Alexis-Bize** [comment]
@Gurrman375 - For security reason, I'll not share the generation process but... Take a look at https://github.com/OpenXbox/xcloud-python/blob/master/xcloud/auth/xal_auth.py which may have what you're looking for ;)

**Comment by Alexis-Bize** [comment]
Released :)
