### ISSUE TITLE
XBOX_APP Client ID Usage

### ISSUE THREAD

**Issue by furey** [XboxReplay/xboxlive-auth#16]
Hi,

Thanks for creating this great little module—I've been wanting to tinker with the Xbox Live API and couldn't get my head around how to generate credentials to do so.

Looking through your implementation, can you please share why `queries.authorize.client_id` references a hardcoded value (`CLIENT_IDS.XBOX_APP` → `'000000004C12AE6F'`):

https://github.com/XboxReplay/xboxlive-auth/blob/7d0b5b7eb1e6eaed8810b4b137ffd6d1a17f9857/src/core/live/config.ts#L1-L20

Where does that `XBOX_APP` value come from and why was it chosen?

Apologies if the answer is obvious and I'm missing something.

Cheers!

😊

**Comment by Alexis-Bize** [comment]
Hey @furey! :) 

This value is the live (live.com) client ID used by the official Xbox desktop / mobile applications during the authentication (OAuth) process.

Each live application has its own ID but this one allows `service::user.auth.xboxlive.com::MBI_SSL` scope usage which skip the authorization prompt and return user's token.

Authorization prompt example:

![Screen Shot 2021-04-08 at 11 17 25](https://user-images.githubusercontent.com/1816892/114001215-04ceb180-985c-11eb-90f4-b0dd1967d386.png)

**Comment by furey** [comment]
@Alexis-Bize Aha—that explains it. Thanks for your time! 😎 ✌️
