### ISSUE TITLE
The provided request must include a 'client_id' input parameter

### ISSUE THREAD

**Issue by ekofi** [XboxReplay/xboxlive-auth#23]
Hi, thanks for the library & your work.

I am using your method (https://github.com/XboxReplay/xboxlive-auth/blob/master/docs/02-Custom_Azure_Application.md), and I filled my CLIENT_ID's, but it says **The provided request must include a 'client_id' input parameter.** Did you know the issue? Thanks!

**Comment by economyplusdev** [comment]
Hello! I was having this issue also, heres the fix!

		const exchangeCodeResponse = await live.exchangeCodeForAccessToken(code, 'clientID', 'scopes', 'redirect url', 'client secret');
		
Have a good day

**Comment by nikolay-keenetic** [comment]
@economyplusdev what should I specify in scopes? permission "User.Read"? I get 'The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.' in the error message

**Comment by economyplusdev** [comment]
Currently using XboxLive.signin XboxLive.offline_access
