### ISSUE TITLE
The dependency Axios has a security breach

### ISSUE THREAD

**Issue by AwesomeCap** [XboxReplay/xboxlive-auth#26]
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/@xboxreplay/xboxlive-auth/node_modules/axios
node_modules/prismarine-auth/node_modules/axios
  @xboxreplay/xboxlive-auth  >=3.0.1
  Depends on vulnerable versions of axios

**Comment by amolinarius** [comment]
Hello,
As the axios syntax hasn't changed, you can just look for `"node_modules/@xboxreplay/xboxlive-auth"` and replace the axios dependency version from `^0.21.1` to `>=0.21.1`, so it will select the most recent version
