### ISSUE TITLE
Cannot exchange "userToken"

### ISSUE THREAD

**Issue by aaron-bond** [XboxReplay/xboxlive-auth#4]
I'm probably doing something pretty dumb but I'm not sure where to debug next. I get a different error if I send through some invalid creds so I know the creds I'm using are valid. I've also not set up 2FA on this account, so don't think that's it.

Where would I be best to look next?

**Comment by Alexis-Bize** [comment]
Hey @aaron-bond, thanks for the report. There is two exposed / non-documented methods which may help you to debug this case.

* Navigate to this [login.live.com](https://login.live.com/oauth20_authorize.srf?client_id=0000000048093EE3&redirect_uri=https://login.live.com/oauth20_desktop.srf&response_type=token&display=touch&scope=XboxLive.signin) link and authenticate.
* Retrieve the `access_token` from query parameters.
* Try the sample below (ES6).

```
import {
    exchangeAccessTokenForUserToken,
    exchangeUserTokenForXSTSIdentity
} from '@xboxreplay/xboxlive-auth';

console.info('Step 1 - Retrive "userToken"');

exchangeAccessTokenForUserToken('RETRIEVED_ACCESS_TOKEN').then(userToken => {
    console.info('Step 1 - Success', userToken);
    console.info('Step 2 - Retrive "XSTSIdentity"');

    return exchangeUserTokenForXSTSIdentity(userToken).then(XSTSIdentity => {
        console.info('Step 2 - Success', XSTSIdentity);
    }).catch(step2Error => {
        console.info('Step 2 - Failed');
        console.error(step2Error);
    });
}).catch(step1Error => {
    console.info('Step 1 - Failed');
    console.error(step1Error);
});
```

**Comment by aaron-bond** [comment]
I just keep getting bad request on this one... 
` curl "https://xsts.auth.xboxlive.com/xsts/authorize" -v -H "x-xbl-contract-version: 0" -H "Content-Type: application/json" -d "{ "RelyingParty": "http://xboxlive.com", "TokenType": "JWT", "Properties": { "UserTokens": ["xxx"], "SandboxId": "RETAIL" } }" `

**Comment by Alexis-Bize** [comment]
Seems like you used double quotes at each parameter even inside the payload which may explain the "Bad Request". Try to use my sample (with single quotes) or escape those in the payload as `\"`.

🕵️ If an error (non-related to the quotes issue) still occurs, here is some questions / propositions.

* Have you ever played with this account?
* Have you ever used this account inside the Xbox App (iOS / Android) or a website like Xbox.com, Mixer.com, etc. 
* Could you try to regenerate an `user_token` via the `exchangeAccessTokenForUserToken` method and replace the `RelyingParty` in the cURL command by `http://mp.microsoft.com/` or `http://beam.pro/`?

Even if I catch it, I've never experimented this issue so thanks for your time!

**Comment by aaron-bond** [comment]
Oh wow - total noob here. I hadn't set that account up as a proper Xbox profile; just a MS account. That's it working now :D 

Thanks for your patience!

**Comment by Alexis-Bize** [comment]
Ay yis! You're welcome :)
