### ISSUE TITLE
Activity confirmation required / Could not match "PPFT" Parameter

### ISSUE THREAD

**Issue by sbauch** [XboxReplay/xboxlive-auth#8]
I'm not really an Xbox user, but am a software engineer collaborating on a project where we would like to use the Xbox API. I've created a MSFT account for Xbox at xbox.com but I do not have an Xbox hardware device.

When I first try to authenticate, I get the `Activity confirmation required`. As instructed, I visited my MSFT account activity page, but am not sure what to do there? It seems like there are successful logins via the API:

<img width="1205" alt="Screen Shot 2020-06-09 at 11 44 22 AM" src="https://user-images.githubusercontent.com/923033/84170841-14b51380-aa48-11ea-9f82-21e3c8a1eb7c.png">

Do I somehow need to "Confirm" this login? How?

Subsequent requests then give the `Could not match "PPFT" Parameter` and do not show up on the account's recent activity page

**Comment by Alexis-Bize** [comment]
Hello @sbauch,

No, there is no "confirm" action on this page but could you try to sign-in on Xbox.com (via http://account.xbox.com/Profile) with the used account? There should be an additional warning / notice about this activity and an additional validation.

Thank you!

**Comment by sbauch** [comment]
Odd, I'm not seeing any such thing

<img width="1145" alt="Screen Shot 2020-06-09 at 12 25 59 PM" src="https://user-images.githubusercontent.com/923033/84174302-711a3200-aa4c-11ea-8ba7-c42bb94637e6.png">

I also pulled the library codebase down and didnt receive any errors when running the e2e test with my account creds

**Comment by Alexis-Bize** [comment]
Mmh, as e2e tests seem to pass I suppose the missing "PPFT parameter" error occurs on a production / test server and not on your local machine, right?

**Comment by sbauch** [comment]
i do get the error on my local machine, but to be clear I'm under the impression this package supports usage in the browser, which seems like it may be the wrong impression?

I can spin up a quick node express app if need be, but had hoped to do this all client side in react native. 

I just tried a similar ruby gem https://github.com/oakesja/xbox-live-api and am able to fetch my profile and such, so it shouldn't be related to the account itself I'd guess?

**Comment by Alexis-Bize** [comment]
Oh! This package can not run inside a browser (CORS issues, and for your own safety to prevent credentials leak). Perhaps It could work inside a React native app but I've never tried.

**Comment by sbauch** [comment]
gotcha yeah, someone had forked this repo and it looked like they got things working with rn, but this all makes a lot of sense. I'll spin up a little API then, thanks for your help!

**Comment by Alexis-Bize** [comment]
You're welcome! I'll update the README and make it clear about its server side usage only.
Closing :)

**Comment by Alexis-Bize** [comment]
@sbauch - Server side this time?
